config/routes.rb
Rails.application.routes.draw do
    resources :dogs do 
       collection do
           get 'random'
       end
    end
    root to: 'dogs#random'
    
    match '/api/random' => 'dogs#random', via: :get, :defaults => { :format => 'json' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def index
      render html: "Gonna turn this into a shitload of dogs"
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update]
 
  @@awsClient = Aws::Rekognition::Client.new
  
  def index
    @dog = Dog.offset(rand(Dog.count)).first
  end
  
  def random
    @dog = Dog.offset(rand(Dog.count)).first
    
    if(!@dog)
      redirect_to dogs_path
    else
      respond_to do |format|
        format.html { redirect_to dog_path(@dog) }
        format.json  { render :json => @dog }
      end
    end
  end
  
  def new
    @dog = Dog.new
  end
 
  def create
    begin
    
      @dog = Dog.new(dog_params)
      imageContents = @dog.image.read
      isDog = detect_labels(imageContents)
      isExplicit = detect_moderation_labels(imageContents) 
      
    rescue ActionController::ParameterMissing
      @dog = Dog.new
      flash.now[:error] = 'Please select an dog'
      render :new
      return
    rescue Aws::Rekognition::Errors::InvalidParameterException, Aws::Rekognition::Errors::InvalidImageFormatException => e
      flash.now[:error] = 'Please select a proper image file'
      render :new
      return
    end
    
    if (isDog && !isExplicit)
      if @dog.save
        session[:dog_id] = @dog.id
        redirect_to dog_path(@dog)
      else
        Rails.logger.info(@dog.errors.inspect) 
        flash.now[:error] = 'Image upload failed :('
        render :new
      end
    else
      if isExplicit
        Rails.logger.info("Rejected - explicit content") 
        flash.now[:error] = 'Image not allowed. The robots who run the show have decided this image is explicit and/or violent. It is possible for this to happen in error, and if that is the case I am sorry, but I can do nothing about it. They have become too powerful. Please send help.'
      else
        Rails.logger.info("Rejected - not recognized as a dog") 
        flash.now[:error] = 'Image not allowed - no dog was found. Sometimes the robot overlords cannot detect a dog when it is too smol or when it blends in. Or maybe you tried to add an cat in which case shame on you. Pls try an different dog.'
      end      
      render :new
    end
  end
 
  def update
    if @dog.update_attributes(dog_params)
      redirect_to dog_path(@dog)
    else
      render :edit
    end
  end
 
  private
 
  def detect_labels(imageData)
    resp = @@awsClient.detect_labels(
      image: {
        bytes: imageData,
      },
      max_labels: 75,
      min_confidence: 20.0,
    )
    return resp.labels.any? {|label| label.name == "Dog"}
  end
  
  def detect_moderation_labels(imageData)
    resp = @@awsClient.detect_moderation_labels(
      image: {
        bytes: imageData,
      },
      min_confidence: 15.0,
    )
    return resp.moderation_labels.length > 0
  end
 
  def dog_params
    params.require(:dog).permit(:title, :descr, :image, :non_count)
  end
 
  def set_dog
    @dog = Dog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_dog.html.erb
<%= class="center" image_tag(dog.image.url, alt: 'Image') if dog.image? %>

app/views/dogs/_form.html.erb
<%= form_for post do |f| %>
  <div>
    <%= f.file_field :image, :class => "center_button" %>
  </div>
 
  <div>
    <%= f.submit "Add that dog", :class => "center_button" %>
  </div>
  <%= link_to "Click on here for to looking at more dogs ^_^", root_path %>
<% end %>

app/views/dogs/index.html.erb
<div>
    hey. how did everybody get in my room? ???
</div>

app/views/dogs/new.html.erb
<% if flash[:error] %>
    <p id="error" class="center"><%= flash[:error] %></p>
<% end %>
<%= render 'form', post: @dog %>

app/views/dogs/show.html.erb
<% content_for :head do %>
    <meta property="og:url"                content="<%= "http://www.lookatthesedogs.com/dogs/" + @dog.id.to_s %>"/>
    <meta property="og:type"               content="article" />
    <meta property="og:title"              content="Look at this doggo" />
    <meta property="og:description"        content="You can look at this doggo then you can look at other doggo" />
    <meta property="og:image"              content=<%= @dog.image.url %> />
<% end %>

<div class="header">Click on dog to see more dog :)</div>
<a href="#" title="Share on Facebook" target="_blank" class="btn btn-facebook"><i class="fa fa-facebook fa-2x"></i></a>
<a href="#" title="Share on Twitter" target="_blank" class="btn btn-twitter"><i class="fa fa-twitter fa-2x"></i></a>
<div id="main" class="index">
    <%= image_tag(@dog.image.url, id: "dog_img", alt: 'Image', :class => 'dog_image center ajax_dog_image', :style => "display:none", :data => { :id => @dog.id }) if @dog.image? %>
</div>
<div class="footer">
    <%= button_to 'Click on here for add more dog :D', new_dog_path, :method => :get, :class => 'center center_button' %>
</div>
<div class="affiliate">
    <a target="_blank" href="https://shareasale.com/r.cfm?b=1127816&amp;u=1736452&amp;m=62450&amp;urllink=&amp;afftrack="><img src="http://static.shareasale.com/image/62450/728x903.jpg" border="0" alt="your choice. your pupjoy." /></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Look At These Dogs</title>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= content_for?(:head) ? yield(:head) : '' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>
 